In [19]:
:my_lst=[1,2,3,4,5]

In [4]:
np.random.random()

0.6436217043480318

In [11]:
np.random.randn()

-1.1419338289886258

In [12]:
import numpy as np 

In [20]:
arr=np.array(my_lst) ## Creating Array using List

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10) # here step is by default 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## Linspace takes third argument as no of point we want
## AND
## arange takes third argument as step we want

In [20]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [23]:
np.linspace(1,10,100)   # it will generate 100 point between 1 and 10

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

## Creating identity matrix:

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random.rand,random.randn ..... & Creation of Array using Builtin Functions

In [2]:
import numpy as np

In [3]:
np.random.rand(4) # generate 4 random number equally distributed

array([0.70377776, 0.53146447, 0.65995053, 0.84402585])

In [27]:
np.random.rand(2,3)

array([[0.88053566, 0.79860312, 0.55703608],
       [0.03260028, 0.46244576, 0.64488222]])

In [4]:
np.random.rand(4,2,3)

array([[[0.98747783, 0.76470201, 0.02602089],
        [0.75098347, 0.78443822, 0.30063531]],

       [[0.67196235, 0.84475303, 0.39006037],
        [0.91009318, 0.68836738, 0.81029382]],

       [[0.33179128, 0.3213894 , 0.11173978],
        [0.26046486, 0.82679986, 0.0583632 ]],

       [[0.70672564, 0.559993  , 0.97362775],
        [0.93195326, 0.57556637, 0.74179683]]])

In [36]:
np.random.randn(4) # generate any 4 number 

array([ 1.88865164, -0.15594022,  2.18585171,  0.29014852])

In [37]:
np.random.randn(2,3)

array([[ 2.67927611, -0.36975818,  0.9122951 ],
       [-0.27006146, -2.86388748, -0.92728027]])

In [3]:
np.random.randint(1,100,10) # it will generate any 10 random integer inclusive 1 and exclusive 100

array([58, 76, 18,  1, 70, 82, 83, 40, 76, 14])

In [5]:
np.random.randint(1,10) # by default it will generate any only one number inclusive 1 and exclusive 10

7

## Some attributes and Methods of Array 

In [5]:
arr=np.arange(25)

In [6]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
ranarr=np.random.randint(1,50,10)

In [8]:
ranarr

array([27, 21, 44, 40, 13, 11, 44, 49,  6, 19])

## Reshaping of given Array

In [9]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Minimum & Maximum Value of given Array

In [10]:
ranarr.max()

49

In [11]:
ranarr.min()

6

## Finding the Index number of Minimum & Maximum Value of Array

In [12]:
ranarr.argmax()

7

In [13]:
ranarr.argmin()

8

In [15]:
arr.shape

(25,)

In [16]:
arr.dtype

dtype('int32')

In [17]:
ranarr.dtype

dtype('int32')

In [8]:
type(ranarr)

numpy.ndarray